version: '3.8'

  actual-budget-sync:
    build: .
    container_name: actual-budget-sync
    ports:
      - "${SYNC_PORT}:3000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      - ACTUAL_SERVER_URL: 'https://${ACTUAL_SERVER_IP}:${ACTUAL_BACKEND_PORT}'
      - ACTUAL_SERVER_PASSWORD: ${ACTUAL_SERVER_PASSWORD}
      - ACTUAL_BUDGET_ID: "${ACTUAL_BUDGET_ID}"
      - ACTUAL_BUDGET_PASSWORD: "${ACTUAL_BUDGET_PASSWORD}"
      - SPREADSHEET_ID: "${SPREADSHEET_ID}"
      - ACCOUNTS_BALANCES_RANGE: "${ACCOUNTS_BALANCES_RANGE}"
      - PRIOR_MONTH_RANGE: "${PRIOR_MONTH_RANGE}"
      - CURRENT_MONTH_RANGE: "${CURRENT_MONTH_RANGE}"
      - SYNC_PORT: "${SYNC_PORT}"
    secrets:
      - google_application_credentials
